- name: Rename All Hostnames
  hosts: all
  roles:
    - common

  tasks:
  - name: set hostname
    become: yes
    hostname:
      name: "{{ element }}"

- name: Update /etc/hosts files
  hosts: all
  roles:
    - common

  tasks:
  - name: template hostname
    become: yes
    template:
      src: hosts.j2
      dest: /etc/hosts 
