- hosts: all
  become: no
  connection: local
  gather_facts: no
  roles:
    - virtual

  tasks:
  - name: create kickstart file
    template:
      src: kickstart.cfg.j2
      dest: "{{ playbook_dir }}/ks/build/{{ inventory_hostname }}.cfg"
